### ISSUE TITLE
Retry mechanism required if Monasca API is temporarily unavailable

### ISSUE THREAD

**Issue by dougszumski** [stackhpc/monasca-monitor#1]
```
Apr 12 08:59:53 mon1 mm-metric-source[6122]: Sending metric: {'jsonbody': [{'timestamp': 1555059593726, 'name': 'monascamonitor.heartbeat', 'dimensions': {'hostname': 'mon1'}, 'value': 0, 'value_meta': None}]}
Apr 12 08:59:53 mon1 mm-metric-source[6122]: Traceback (most recent call last):
Apr 12 08:59:53 mon1 mm-metric-source[6122]: File "/opt/monasca-monitor/bin/mm-metric-source", line 10, in <module>
Apr 12 08:59:53 mon1 mm-metric-source[6122]: sys.exit(main())
Apr 12 08:59:53 mon1 mm-metric-source[6122]: File "/opt/monasca-monitor/lib/python2.7/site-packages/monasca_monitor/metrics_source.py", line 106, in main
Apr 12 08:59:53 mon1 mm-metric-source[6122]: metricsource.send_metric()
Apr 12 08:59:53 mon1 mm-metric-source[6122]: File "/opt/monasca-monitor/lib/python2.7/site-packages/monasca_monitor/metrics_source.py", line 100, in send_metric
Apr 12 08:59:53 mon1 mm-metric-source[6122]: MetricSource._send_heartbeat_metric(self.monasca_client)
Apr 12 08:59:53 mon1 mm-metric-source[6122]: File "/opt/monasca-monitor/lib/python2.7/site-packages/monasca_monitor/metrics_source.py", line 97, in _send_heartbeat_metric
Apr 12 08:59:53 mon1 mm-metric-source[6122]: client.metrics.create(**kwargs)
Apr 12 08:59:53 mon1 mm-metric-source[6122]: File "/opt/monasca-monitor/lib/python2.7/site-packages/monascaclient/v2_0/metrics.py", line 31, in create
Apr 12 08:59:53 mon1 mm-metric-source[6122]: body = self.client.create(url=url_str, json=data)
Apr 12 08:59:53 mon1 mm-metric-source[6122]: File "/opt/monasca-monitor/lib/python2.7/site-packages/osc_lib/api/api.py", line 164, in create
Apr 12 08:59:53 mon1 mm-metric-source[6122]: ret = self._request(method, url, session=session, **params)
Apr 12 08:59:53 mon1 mm-metric-source[6122]: File "/opt/monasca-monitor/lib/python2.7/site-packages/osc_lib/api/api.py", line 141, in _request
Apr 12 08:59:53 mon1 mm-metric-source[6122]: return session.request(url, method, **kwargs)
Apr 12 08:59:53 mon1 mm-metric-source[6122]: File "/opt/monasca-monitor/lib/python2.7/site-packages/keystoneauth1/session.py", line 814, in request
Apr 12 08:59:53 mon1 mm-metric-source[6122]: resp = send(**kwargs)
Apr 12 08:59:53 mon1 mm-metric-source[6122]: File "/opt/monasca-monitor/lib/python2.7/site-packages/keystoneauth1/session.py", line 919, in _send_request
Apr 12 08:59:53 mon1 mm-metric-source[6122]: raise exceptions.ConnectFailure(msg)
Apr 12 08:59:53 mon1 mm-metric-source[6122]: keystoneauth1.exceptions.connection.ConnectFailure: Unable to establish connection to http://10.10.10.2:8082/v2.0/metrics: ('Connection aborted.', BadStatusLine("''",))
Apr 12 08:59:53 mon1 systemd[1]: monasca-monitor-metric-source.service: main process exited, code=exited, status=1/FAILURE
Apr 12 08:59:53 mon1 systemd[1]: Unit monasca-monitor-metric-source.service entered failed state.
Apr 12 08:59:53 mon1 systemd[1]: monasca-monitor-metric-source.service failed.
```

**Comment by Wasaac** [comment]
```
Sep 03 07:24:48 mm-metric-source[21817]: Traceback (most recent call last):
Sep 03 07:24:48 mm-metric-source[21817]: File "/opt/monasca-monitor/bin/mm-metric-source", line 10, in <module>
Sep 03 07:24:48 mm-metric-source[21817]: sys.exit(main())
Sep 03 07:24:48 mm-metric-source[21817]: File "/opt/monasca-monitor/lib/python2.7/site-packages/monasca_monitor/metrics_source.py", line 111, in main
Sep 03 07:24:48 mm-metric-source[21817]: metricsource.send_metric()
Sep 03 07:24:48 mm-metric-source[21817]: File "/opt/monasca-monitor/lib/python2.7/site-packages/monasca_monitor/metrics_source.py", line 105, in send_metric
Sep 03 07:24:48 mm-metric-source[21817]: MetricSource._send_heartbeat_metric(self.monasca_client)
Sep 03 07:24:48 mm-metric-source[21817]: File "/opt/monasca-monitor/lib/python2.7/site-packages/monasca_monitor/metrics_source.py", line 99, in _send_heartbeat_
Sep 03 07:24:48 mm-metric-source[21817]: client.metrics.create(**kwargs)
Sep 03 07:24:48 mm-metric-source[21817]: File "/opt/monasca-monitor/lib/python2.7/site-packages/monascaclient/v2_0/metrics.py", line 31, in create
Sep 03 07:24:48 mm-metric-source[21817]: body = self.client.create(url=url_str, json=data)
Sep 03 07:24:48 mm-metric-source[21817]: File "/opt/monasca-monitor/lib/python2.7/site-packages/osc_lib/api/api.py", line 164, in create
Sep 03 07:24:48 mm-metric-source[21817]: ret = self._request(method, url, session=session, **params)
Sep 03 07:24:48 mm-metric-source[21817]: File "/opt/monasca-monitor/lib/python2.7/site-packages/osc_lib/api/api.py", line 141, in _request
Sep 03 07:24:48 mm-metric-source[21817]: return session.request(url, method, **kwargs)
Sep 03 07:24:48 mm-metric-source[21817]: File "/opt/monasca-monitor/lib/python2.7/site-packages/keystoneauth1/session.py", line 814, in request
Sep 03 07:24:48 mm-metric-source[21817]: resp = send(**kwargs)
Sep 03 07:24:48 mm-metric-source[21817]: File "/opt/monasca-monitor/lib/python2.7/site-packages/keystoneauth1/session.py", line 910, in _send_request
Sep 03 07:24:48 mm-metric-source[21817]: raise exceptions.ConnectTimeout(msg)
Sep 03 07:24:48 mm-metric-source[21817]: keystoneauth1.exceptions.connection.ConnectTimeout: Request to http://10.114.129.2:8082/v2.0/metrics timed out
Sep 03 07:24:48 systemd[1]: monasca-monitor-metric-source.service: main process exited, code=exited, status=1/FAILURE
Sep 03 07:24:48 systemd[1]: Unit monasca-monitor-metric-source.service entered failed state.
Sep 03 07:24:48 systemd[1]: monasca-monitor-metric-source.service failed.
```

**Comment by dougszumski** [comment]
This is closed for the above two cases.
